-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jun 09, 2012 at 11:45 AM
-- Server version: 5.1.44
-- PHP Version: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `test`
--

-- --------------------------------------------------------

--
-- Table structure for table `Images`
--

CREATE TABLE IF NOT EXISTS `Images` (
  `id` int(11) NOT NULL,
  `name` text,
  `description` text,
  `imageURL` text,
  `imageThumbURL` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Images`
--

INSERT INTO `Images` (`id`, `name`, `description`, `imageURL`, `imageThumbURL`) VALUES
(5497, 'Osaka 28', 'Although stunning from the street, the Osaka is a lot more than it appears. No matter how you spend your home time, when you spend it in the Osaka, it’s rich, rewarding and memorable.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/osaka_facade_1.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/osaka_plan_28_flip.jpg'),
(5498, 'Milan 35', 'Equally appealing inside and out, the Milan is a stylish and contemporary home, without even a hint of pretension.', 'http://www.boutiquehomes.com.au/sites/default/files/milan_facade_1.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/milan_plan_35_flip.jpg'),
(5499, 'Montreal 25', 'With its sleek yet practical narrow design, the Montreal is an impressive single storey home that fits comfortably on a 12.5m wide block. The home’s streamlined design has many benefits.', 'http://www.boutiquehomes.com.au/sites/default/files/montreal_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/montreal_plan_a_flip.jpg'),
(5500, 'Knightsbridge 26', 'Two things set the Knightsbridge apart: Distinctive design and exclusive style. Both are immediately apparent the moment you walk in the front door. It starts with privacy. From the front porch — even from inside the entry hall — all living spaces remain completely obscured.', 'http://www.boutiquehomes.com.au/sites/default/files/knightsbridge_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/knightsbridge_plan_26_flip.jpg'),
(5501, 'Toorak 28', 'The Toorak makes no apologies for its impeccable design and exclusive comfort. Nor for the privileged lifestyle it delivers. Yet for all its elegance, it is nonetheless a warm and friendly home, designed to always meet your family’s ever-changing needs.', 'http://www.boutiquehomes.com.au/sites/default/files/toorak_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/toorak_plan_28_flip.jpg'),
(5502, 'Verve 38', 'The Verve is more than majestic. An immensely spacious two-storey home, it’s at once sophisticated and cleverly laid out, yet still lavishly stylish and full of life.', 'http://www.boutiquehomes.com.au/sites/default/files/verve_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/verve_plan_38_flip.jpg'),
(5503, 'Vogue 34', 'As the name suggests, this home epitomises cutting-edge style. Born out of a lovingly designed floor plan, it delivers living spaces that are at once fashionable and contemporary, yet still undeniably comfortable.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/vogue_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/vogue_plan_34_flip.jpg'),
(5504, 'Rio 26', 'The Rio is a spacious family home that makes living - real living - its highest priority. The floor plan is cleverly zoned with all living areas down one side of the home, and all bedrooms down the other. ', 'http://www.boutiquehomes.com.au/sites/default/files/K9%2520Facade%2520Renaissance_1.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/rio_plan_a_flipped_0.jpg'),
(5505, 'Alpine Villa 25', 'Fresh, open and designed for living, this generously proportioned three or four bedroom home is a villa in every sense but size. From its stunning raking ceiling in the open plan living area, to its ‘tucked-away’ home theatre, it makes every moment at home an escape.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/alpinevilla_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/alpinevilla_plan_25_flip.jpg'),
(5506, 'Alpine Villa 27', 'Fresh, open and designed for living, this generously proportioned three or four bedroom home is a villa in every sense but size. From its stunning raking ceiling in the open plan living area, to its ‘tucked-away’ home theatre, it makes every moment at home an escape.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/alpinevilla_facade_1.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/alpinevilla_plan_27_flip.jpg'),
(5507, 'Alpine Villa 29', 'Fresh, open and designed for living, this generously proportioned three or four bedroom home is a villa in every sense but size. From its stunning raking ceiling in the open plan living area, to its ‘tucked-away’ home theatre, it makes every moment at home an escape.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/alpinevilla_facade_2.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/alpinevilla_plan_29_flip.jpg'),
(5508, 'Aspen 27', 'Perfect for rest, work and play, the Aspen offers practical luxury with a distinctive alpine feel. Stunning raked ceilings accent its generous, open-plan living area, from kitchen through to living room — and large timber-framed windows deliver an uplifting outlook (even if you’re a world away from the ski slopes!).', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/aspen_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/aspen_plan_27_flip.jpg'),
(5509, 'Aspen 29', 'Perfect for rest, work and play, the Aspen offers practical luxury with a distinctive alpine feel. Stunning raked ceilings accent its generous, open-plan living area, from kitchen through to living room — and large timber-framed windows deliver an uplifting outlook (even if you’re a world away from the ski slopes!).', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/aspen_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/aspen_plan_29_flip.jpg'),
(5510, 'Edmonton 25', 'The Edmonton was designed with one thing in mind: your lifestyle. Named after Canada’s ‘Festival City’, it includes all those extra little features you''''ve come to expect in a home, as well as those you’ve always wanted. Features that make every day a celebration.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/edmonton_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/edmonton_plan_25_flip.jpg'),
(5511, 'Greenwich 37', 'The Greenwich is a beautifully designed and crafted prestige family home. Rich with all the luxury offerings you’d expect from a Boutique home, it’s at once magnificent and stately, yet still charming and comfortable.', 'http://www.boutiquehomes.com.au/sites/default/files/greenwich_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/greenwich_plan_37_flip.jpg'),
(5512, 'Horizon 24', 'Stylish design is an excellent start. But only when a house makes you feel at home is it truly a home. The Horizon most definitely ticks both boxes.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/horizon_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/horizon_plan_24_flip.jpg'),
(5513, 'Knightsbridge 29', 'Two things set the Knightsbridge apart: Distinctive design and exclusive style. Both are immediately apparent the moment you walk in the front door. It starts with privacy. From the front porch — even from inside the entry hall — all living spaces remain completely obscured. ', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/knightsbridge_facade_1.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/knightsbridge_plan_29_flip.jpg'),
(5514, 'Madison 33', 'This undeniably fashionable double storey house is no ordinary home. It was designed with a difference. Despite boasting a generous 33 squares, it still manages to fit on a 12.5m wide block, and to fit comfortably. But that’s just the tip of the iceberg.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/madison_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/madison_plan_33_flip.jpg'),
(5515, 'Manhattan 37', 'Reminiscent of a stylish downtown New York apartment, the Manhattan combines contemporary sophistication with state-of-the-art innovation.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/manhattan_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/manhattan_plan_37_flip.jpg'),
(5516, 'Manhattan 42', 'Reminiscent of a stylish downtown New York apartment, the Manhattan combines contemporary sophistication with state-of-the-art innovation.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/manhattan_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/manhattan_plan_42_flip.jpg'),
(5517, 'Milan 40', 'Equally appealing inside and out, the Milan is a stylish and contemporary home, without even a hint of pretension.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/milan_facade_1_2.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/milan_plan_40_flip.jpg'),
(5518, 'Osaka 32', 'Although stunning from the street, the Osaka is a lot more than it appears. No matter how you spend your home time, when you spend it in the Osaka, it’s rich, rewarding and memorable.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/osaka_facade_2.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/osaka_plan_32_flip..jpg'),
(5519, 'Regent 33', 'It may be the pinnacle in international style and luxury, but the Regent is nonetheless the perfect family home. Its master bedroom has been thoughtfully positioned on the ground floor, away from the minor bedrooms, which are all located on the second storey.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/regent_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/regent_plan_33_flip_0.jpg'),
(5520, 'Regent 36', 'It may be the pinnacle in international style and luxury, but the Regent is nonetheless the perfect family home. Its master bedroom has been thoughtfully positioned on the ground floor, away from the minor bedrooms, which are all located on the second storey.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/regent_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/regent_plan_36_0.jpg'),
(5521, 'Residence 46', 'The Residence is designed for refined relaxation. From the luxuriously oversized master bedroom with lavishly appointed ensuite, to the secluded home office, right through to the upstairs kids’ area with rumpus/games room...', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/residence_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/residence_plan_46_flip.jpg'),
(5522, 'Residence 36', 'The Residence is designed for refined relaxation. From the luxuriously oversized master bedroom with lavishly appointed ensuite, to the secluded home office, right through to the upstairs kids’ area with rumpus/games room...', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/residence_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/residence_plan_36_flip.jpg'),
(5523, 'Toorak 32', 'The Toorak makes no apologies for its impeccable design and exclusive comfort. Nor for the privileged lifestyle it delivers. Yet for all its elegance, it is nonetheless a warm and friendly home, designed to always meet your family’s ever-changing needs.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/toorak_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/toorak_plan_32_flip.jpg'),
(5524, 'Verve 41', 'The Verve is more than majestic. An immensely spacious two-storey home, it’s at once sophisticated and cleverly laid out, yet still lavishly stylish and full of life.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/verve_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/verve_plan_41_flip.jpg'),
(5525, 'Vogue 28', 'As the name suggests, this home epitomises cutting-edge style. Born out of a lovingly designed floor plan, it delivers living spaces that are at once fashionable and contemporary, yet still undeniably comfortable.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/vogue_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/vogue_plan_28_flip.jpg'),
(5526, 'Westend 28', 'Stand out on the street for all the right reasons, in the stunning Westend. With a contemporary yet functional design the Westend is unashamedly upmarket, yet ideal for today''''s modern family.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/westend_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/westend_plan_28_flip.jpg'),
(5527, 'Westend 31', 'Stand out on the street for all the right reasons, in the stunning Westend. With a contemporary yet functional design the Westend is unashamedly upmarket, yet ideal for today''''s modern family.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/westend_facade_1.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/westend_plan_31_flip.jpg'),
(5528, 'St Tropez 26', 'The St Tropez is an architectural playground for family and guests alike and nothing short of stylish innovative living. This Euro inspired, opulent home combines unique style and zoned living within a functional design that compliments today''''s busy lifestyles.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/sttropez_cr_facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/sttropez_plan_26_flip.jpg'),
(5529, 'St Tropez 29', 'The St Tropez is an architectural playground for family and guests alike and nothing short of stylish innovative living. This Euro inspired, opulent home combines unique style and zoned living within a functional design that compliments today''''s busy lifestyles.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/sttropez_cr_facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/sttropez_plan_29_flip_0.jpg'),
(5530, 'Monte Carlo 33', 'Live a life of glamour and luxury in this double storey, four bedroom Monte Carlo masterpiece. Work from your home office at the front of the house before retiring upstairs to unwind and enjoy the scenery from your master bedroom balcony. When it’s time to entertain, the possibilities are endless with a spacious kitchen featuring an island bench and walk-in pantry, an open plan dining and living space, and a covered outdoor living area.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Monte%20Carlo%20external.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/monte-33-first_0.jpg'),
(5531, 'Monte Carlo 36', 'Live a life of glamour and luxury in this double storey, four bedroom Monte Carlo masterpiece. Work from your home office at the front of the house before retiring upstairs to unwind and enjoy the scenery from your master bedroom balcony. When it’s time to entertain, the possibilities are endless with a spacious kitchen featuring an island bench and walk-in pantry, an open plan dining and living space, and a covered outdoor living area.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Monte%20Carlo%20external_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/first-floor-carlo.jpg'),
(5532, 'Santa Monica 25', 'You’ll feel like you’re on vacation all year round in the spacious Santa Monica. Relax in the master bedroom with ensuite and walk-in robe, or head down to the home theatre to watch a movie with the kids. Stay central to the action in the gourmet kitchen with versatile island bench that doubles as a drinks or breakfast bar. Throw open the folding doors and join the indoor and outdoor living areas for perfect entertaining.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Santa%20Monica%20external.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/floor-plan-santa-mon.jpg'),
(5533, 'Santa Monica 28', 'You’ll feel like you’re on vacation all year round in the spacious four bedroom Santa Monica. Relax in the master bedroom with ensuite and walk-in robe, or head down to the home theatre to watch a movie with the kids. Stay central to the action in the gourmet kitchen with versatile island bench that doubles as a drinks or breakfast bar. Throw open the folding doors and join the indoor and outdoor living areas for perfect entertaining.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Santa%20Monica%20external_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/Santa-Monica-28-floorplan.jpg'),
(5534, 'Knightsbridge 26', 'Two things set the Knightsbridge apart: Distinctive design and exclusive style. Both are immediately apparent the moment you walk in the front door. It starts with privacy. From the front porch — even from inside the entry hall — all living spaces remain completely obscured.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/BH_StTropez_001.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/Knightsbridge%2026.JPG'),
(5535, 'K1 Alpha', 'Spread over two floors the K1 provides freestanding, spacious luxury. This 33sq, three bedroom home features three bedrooms, home office and spacious open plan living.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/alpine-cropped.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K1%20Alpha%20floorplan_0.JPG'),
(5536, 'Studio 25', 'This cleverly designed home ensures everyone has their own space with four spacious bedrooms and open plan kitchen, dining and living.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/HB_Craigieburn_Studi%23113181.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/Studio%2025%20floorplan_0.JPG'),
(5537, 'Sanctuary 25', 'This stunning 4 bedroom, 2 bathroom home also boasts a home cinema and easy, outdoor living opening from the lounge area.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Retreat-Facade%20MAY%202010.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/Sanctuary%2025%20floorplan.JPG'),
(5538, 'Test Thing', '', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Tulips_3.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/Sanctuary%2025%20floorplan.JPG'),
(5539, 'K10 Professional', 'The K10 provides spacious open plan family living with three spacious bedrooms, two bathrooms and generous outdoor alfresco area under the main roof line providing truly intergrated outdoor living.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/K10%20Coburg%20Hill.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K10%20floorplan.JPG'),
(5540, 'Portsea', 'There''''s a special place for everyone who enters the Portsea', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Portsea_Lot944.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/Portsea%20Floorplan.jpg'),
(5541, 'K5 Perspective', 'A stunning 26 sq home, designed perfectly for any family, the K5 provides a luxury retreat in every point of the home. With a beautifully designed open plan setting, all bedrooms located upstairs, and a balcony this home provides a space for everyone to enjoy.  ', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Coburg-Hill-K5-Modern-Perspective-Facade_0-CROPPED_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K5%20Perspective%20floorplan.JPG'),
(5542, 'K1 Aspect', 'Spread over two floors the K1 provides freestanding, spacious luxury. This 33sq, three bedroom home features three bedrooms, home office and spacious open plan living.', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Coburg%20Hill%20K1%20Architectural%20Aspect%20Facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K1%20Alpha%20floorplan.JPG'),
(5543, 'Studio 22 - Clyde North', '', 'http://www.boutiquehomes.com.au/sites/default/files/designs/gallery/Studio-016_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/Cob%20Street%2C%20Clyde%20North.JPG'),
(5544, 'K1 Allure', 'Spread over two floors the K1 provides freestanding, spacious luxury. This 33sq home features three bedrooms, home office and spacious open plan living incorporating kitchen, living and dining. Sliding doors allow the living area to be extended outdoors, underneath the covered alfresco area.', 'http://www.boutiquehomes.com.au/sites/default/files/Coburg%2520Hill%2520K1%2520Modern%2520Allure%2520Facade_text.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K1%20Allure%20floorplan.JPG'),
(5545, 'K4 Ascent', 'A stunning home with an eye catching facade, the K4 provides an abundance of space and open plan living – perfect for entertaining. The gourmet kitchen with walk-in pantry and large island bench is any aspiring chef’s dream along with the outdoor living area opening from the dining and living area.', 'http://www.boutiquehomes.com.au/sites/default/files/Coburg%20Hill%20K4%20Architectural%20Ascent%20Facade_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K4%20floorplan_0.JPG'),
(5546, 'K6 Professional', 'Luxury family living is what you will find in this stylish 18sq home. ', 'http://www.boutiquehomes.com.au/sites/default/files/Coburg%20Hill%20K6%20Architectural%20Professional%20Facade.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K6%20Floorplan_0.JPG'),
(5547, 'K9 Renaissance', 'The K9 is a s[acious family home that makes living - real living - its highest priority.', 'http://www.boutiquehomes.com.au/sites/default/files/K9%2520Facade%2520Renaissance_0.jpg', 'http://www.boutiquehomes.com.au/sites/default/files/designs/floorplans/K9%20Renaissance%20floorplan.JPG');
